// Auto-generated by design_cic_comp_fir.py
/*
Architecture:
  * Type I symmetric FIR (linear phase, required for STFFT)
  * Pre-adder structure  → halves the number of multiply operations
  * CSD shift-add trees  → zero multiplier cells (hardwired shifts only)
  * AXI-Stream ready/valid handshake on both input and output ports

I/O widths:
  IW  = input word width  (CIC output, truncated/rounded)
  CW  = coefficient bits  (14)
  OW  = output word width = IW + CW + ceil(log2(NTAPS)) + 1 guard

Integration:
  Connect CIC output_tdata (truncated to IW bits) → i_tdata.
  i_tvalid / i_tready form the upstream handshake.
  o_tvalid / o_tready form the downstream handshake.
  o_tdata feeds directly into STFFT i_sample port.

Back-pressure behaviour:
  The FIR is a single-stage pipeline (1-cycle latency).  Standard
  1-deep pipeline handshake:
    i_tready = !o_tvalid || o_tready
  This means:
    - We accept a new input whenever the output slot is empty, OR the
      downstream is simultaneously consuming the current output.
    - If downstream stalls (o_tready=0) and we have valid output, we
      hold both the output register AND the delay line (no new sample
      is consumed from upstream until the stall clears).
*/

//     set_dont_use [get_lib_cells *MULT*]

`default_nettype none

module compFIR #(
    parameter NTAPS = 33,   // Total taps (must be odd)
    parameter IW    = 16,   // Input word width
    parameter CW    = 14,   // Coefficient word width
    parameter OW    = 37    // Output width = IW+CW+ceil(log2(NTAPS))+1
) (
    input  wire                   i_clk,
    input  wire                   i_reset,

    // ── Upstream (from CIC decimator) ──────────────────────────────────────
    input  wire signed [IW-1:0]   i_tdata,
    input  wire                   i_tvalid,
    output wire                   i_tready,

    // ── Downstream (to STFFT) ──────────────────────────────────────────────
    output reg  signed [OW-1:0]   o_tdata,
    output reg                    o_tvalid,
    input  wire                   o_tready
);

    localparam M  = (NTAPS-1)/2;   // Index of centre tap

    // Handshake
    //
    // We can accept a new sample when the output slot is empty OR the
    // downstream is consuming it this cycle (1-deep pipeline).
    assign i_tready = !o_tvalid || o_tready;
    
    wire advance = i_tvalid && i_tready;  // a new sample is accepted this cycle

    // Delay line — advances only when we accept a new sample
    reg signed [IW-1:0] sr [0:NTAPS-1];
    integer i;
    always @(posedge i_clk) begin
        if (i_reset) begin
            for (i = 0; i < NTAPS; i = i+1) sr[i] <= 0;
        end else if (advance) begin
            for (i = NTAPS-1; i > 0; i = i-1) sr[i] <= sr[i-1];
            sr[0] <= i_tdata;
        end
    end

    // Next-state delay line (combinational view of "after shift")
    wire signed [IW-1:0] sr_next [0:NTAPS-1];

    assign sr_next[0] = i_tdata;

    genvar si;
    generate
    for (si = 1; si < NTAPS; si = si+1) begin : SR_NEXT_GEN
        assign sr_next[si] = sr[si-1];
    end
    endgenerate

    // Pre-adders (use next-state when advancing, otherwise hold state)
    wire signed [IW:0] sym [0:M];

    genvar k;
    generate
    for (k = 0; k < M; k = k+1) begin : PREADD
        wire signed [IW-1:0] a = advance ? sr_next[k] : sr[k];
        wire signed [IW-1:0] b = advance ? sr_next[NTAPS-1-k] : sr[NTAPS-1-k];

        assign sym[k] = $signed({a[IW-1], a}) +
                        $signed({b[IW-1], b});
    end
    endgenerate

    wire signed [IW-1:0] mid = advance ? sr_next[M] : sr[M];
    assign sym[M] = $signed({mid[IW-1], mid});

    // CSD multiply  (shift-add, no multiplier cells)
    // PW = IW+CW+1 = 31
    wire signed [OW-1:0] prod [0:M];

    // tap k=0: +11952  CSD: +2^14  -2^12  -2^8  -2^6  -2^4
    assign prod[0] = ($signed({{OW-IW-1{sym[0][IW]}}, sym[0]}) <<< 14) - ($signed({{OW-IW-1{sym[0][IW]}}, sym[0]}) <<< 12) - ($signed({{OW-IW-1{sym[0][IW]}}, sym[0]}) <<< 8) - ($signed({{OW-IW-1{sym[0][IW]}}, sym[0]}) <<< 6) - ($signed({{OW-IW-1{sym[0][IW]}}, sym[0]}) <<< 4);

    // tap k=1: -2084  CSD: -2^11  -2^5  -2^2
    assign prod[1] = -($signed({{OW-IW-1{sym[1][IW]}}, sym[1]}) <<< 11) - ($signed({{OW-IW-1{sym[1][IW]}}, sym[1]}) <<< 5) - ($signed({{OW-IW-1{sym[1][IW]}}, sym[1]}) <<< 2);

    // tap k=2: -77  CSD: -2^6  -2^4  +2^2  -2^0
    assign prod[2] = -($signed({{OW-IW-1{sym[2][IW]}}, sym[2]}) <<< 6) - ($signed({{OW-IW-1{sym[2][IW]}}, sym[2]}) <<< 4) + ($signed({{OW-IW-1{sym[2][IW]}}, sym[2]}) <<< 2) - $signed({{OW-IW-1{sym[2][IW]}}, sym[2]});

    // tap k=3: +699  CSD: +2^10  -2^8  -2^6  -2^2  -2^0
    assign prod[3] = ($signed({{OW-IW-1{sym[3][IW]}}, sym[3]}) <<< 10) - ($signed({{OW-IW-1{sym[3][IW]}}, sym[3]}) <<< 8) - ($signed({{OW-IW-1{sym[3][IW]}}, sym[3]}) <<< 6) - ($signed({{OW-IW-1{sym[3][IW]}}, sym[3]}) <<< 2) - $signed({{OW-IW-1{sym[3][IW]}}, sym[3]});

    // tap k=4: -845  CSD: -2^10  +2^8  -2^6  -2^4  +2^2  -2^0
    assign prod[4] = -($signed({{OW-IW-1{sym[4][IW]}}, sym[4]}) <<< 10) + ($signed({{OW-IW-1{sym[4][IW]}}, sym[4]}) <<< 8) - ($signed({{OW-IW-1{sym[4][IW]}}, sym[4]}) <<< 6) - ($signed({{OW-IW-1{sym[4][IW]}}, sym[4]}) <<< 4) + ($signed({{OW-IW-1{sym[4][IW]}}, sym[4]}) <<< 2) - $signed({{OW-IW-1{sym[4][IW]}}, sym[4]});

    // tap k=5: +802  CSD: +2^10  -2^8  +2^5  +2^1
    assign prod[5] = ($signed({{OW-IW-1{sym[5][IW]}}, sym[5]}) <<< 10) - ($signed({{OW-IW-1{sym[5][IW]}}, sym[5]}) <<< 8) + ($signed({{OW-IW-1{sym[5][IW]}}, sym[5]}) <<< 5) + ($signed({{OW-IW-1{sym[5][IW]}}, sym[5]}) <<< 1);

    // tap k=6: -680  CSD: -2^9  -2^7  -2^5  -2^3
    assign prod[6] = -($signed({{OW-IW-1{sym[6][IW]}}, sym[6]}) <<< 9) - ($signed({{OW-IW-1{sym[6][IW]}}, sym[6]}) <<< 7) - ($signed({{OW-IW-1{sym[6][IW]}}, sym[6]}) <<< 5) - ($signed({{OW-IW-1{sym[6][IW]}}, sym[6]}) <<< 3);

    // tap k=7: +533  CSD: +2^9  +2^4  +2^2  +2^0
    assign prod[7] = ($signed({{OW-IW-1{sym[7][IW]}}, sym[7]}) <<< 9) + ($signed({{OW-IW-1{sym[7][IW]}}, sym[7]}) <<< 4) + ($signed({{OW-IW-1{sym[7][IW]}}, sym[7]}) <<< 2) + $signed({{OW-IW-1{sym[7][IW]}}, sym[7]});

    // tap k=8: -390  CSD: -2^9  +2^7  -2^3  +2^1
    assign prod[8] = -($signed({{OW-IW-1{sym[8][IW]}}, sym[8]}) <<< 9) + ($signed({{OW-IW-1{sym[8][IW]}}, sym[8]}) <<< 7) - ($signed({{OW-IW-1{sym[8][IW]}}, sym[8]}) <<< 3) + ($signed({{OW-IW-1{sym[8][IW]}}, sym[8]}) <<< 1);

    // tap k=9: +267  CSD: +2^8  +2^4  -2^2  -2^0
    assign prod[9] = ($signed({{OW-IW-1{sym[9][IW]}}, sym[9]}) <<< 8) + ($signed({{OW-IW-1{sym[9][IW]}}, sym[9]}) <<< 4) - ($signed({{OW-IW-1{sym[9][IW]}}, sym[9]}) <<< 2) - $signed({{OW-IW-1{sym[9][IW]}}, sym[9]});

    // tap k=10: -169  CSD: -2^7  -2^5  -2^3  -2^0
    assign prod[10] = -($signed({{OW-IW-1{sym[10][IW]}}, sym[10]}) <<< 7) - ($signed({{OW-IW-1{sym[10][IW]}}, sym[10]}) <<< 5) - ($signed({{OW-IW-1{sym[10][IW]}}, sym[10]}) <<< 3) - $signed({{OW-IW-1{sym[10][IW]}}, sym[10]});

    // tap k=11: +99  CSD: +2^7  -2^5  +2^2  -2^0
    assign prod[11] = ($signed({{OW-IW-1{sym[11][IW]}}, sym[11]}) <<< 7) - ($signed({{OW-IW-1{sym[11][IW]}}, sym[11]}) <<< 5) + ($signed({{OW-IW-1{sym[11][IW]}}, sym[11]}) <<< 2) - $signed({{OW-IW-1{sym[11][IW]}}, sym[11]});

    // tap k=12: -53  CSD: -2^6  +2^4  -2^2  -2^0
    assign prod[12] = -($signed({{OW-IW-1{sym[12][IW]}}, sym[12]}) <<< 6) + ($signed({{OW-IW-1{sym[12][IW]}}, sym[12]}) <<< 4) - ($signed({{OW-IW-1{sym[12][IW]}}, sym[12]}) <<< 2) - $signed({{OW-IW-1{sym[12][IW]}}, sym[12]});

    // tap k=13: +25  CSD: +2^5  -2^3  +2^0
    assign prod[13] = ($signed({{OW-IW-1{sym[13][IW]}}, sym[13]}) <<< 5) - ($signed({{OW-IW-1{sym[13][IW]}}, sym[13]}) <<< 3) + $signed({{OW-IW-1{sym[13][IW]}}, sym[13]});

    // tap k=14: -10  CSD: -2^3  -2^1
    assign prod[14] = -($signed({{OW-IW-1{sym[14][IW]}}, sym[14]}) <<< 3) - ($signed({{OW-IW-1{sym[14][IW]}}, sym[14]}) <<< 1);

    // tap k=15: +3  CSD: +2^2  -2^0
    assign prod[15] = ($signed({{OW-IW-1{sym[15][IW]}}, sym[15]}) <<< 2) - $signed({{OW-IW-1{sym[15][IW]}}, sym[15]});

    // tap k=16: -1  CSD: -2^0
    assign prod[16] = -$signed({{OW-IW-1{sym[16][IW]}}, sym[16]});

    // Output register  —  advances only when we accept a new sample
    // o_tvalid is set one cycle after the first accepted sample,
    // cleared only on reset.
    always @(posedge i_clk) begin
        if (i_reset) begin
            o_tdata  <= 0;
            o_tvalid <= 0;
        end else if (advance) begin
            o_tdata  <= prod[0]
                      + prod[1]
                      + prod[2]
                      + prod[3]
                      + prod[4]
                      + prod[5]
                      + prod[6]
                      + prod[7]
                      + prod[8]
                      + prod[9]
                      + prod[10]
                      + prod[11]
                      + prod[12]
                      + prod[13]
                      + prod[14]
                      + prod[15]
                      + prod[16];
            o_tvalid <= 1;
        end else if (o_tready) begin
            // Downstream consumed the output but no new sample arrived;
            // de-assert valid so downstream knows the slot is empty.
            o_tvalid <= 0;
        end
    end

endmodule