MAKEFILE_DIR := $(shell dirname $(realpath $(firstword $(MAKEFILE_LIST))))

RUN_TAG = $(shell ls librelane/runs/ | tail -n 1)
TOP = chip_top

PDK_ROOT ?= $(MAKEFILE_DIR)/gf180mcu
PDK ?= gf180mcuD
PDK_COMMIT ?= d658698bd8bcf4e05fc7b5991a701247ba0d744c
SCL ?= gf180mcu_as_sc_mcu7t3v3

AVAILABLE_SLOTS = 1x1 0p5x1 1x0p5 0p5x0p5
DEFAULT_SLOT = 1x1

# Slot can be any of AVAILABLE_SLOTS
SLOT ?= $(DEFAULT_SLOT)

ifeq ($(SLOT),default)
	SLOT = $(DEFAULT_SLOT)
endif

ifeq ($(filter $(SLOT),$(AVAILABLE_SLOTS)),)
	$(error $(SLOT) does not exist in AVAILABLE_SLOTS: $(AVAILABLE_SLOTS))
endif

ifeq ($(SCL),default)
	SCL = gf180mcu_as_sc_mcu7t3v3
endif
SCL ?= gf180mcu_as_sc_mcu7t3v3

ifeq ($(PAD),default)
	PAD = gf180mcu_fd_io
endif
PAD ?= gf180mcu_fd_io

ifeq ($(SRAM),default)
	SRAM = gf180mcu_ocd_ip_sram
endif
SRAM ?= gf180mcu_ocd_ip_sram

ifeq ($(SRAM),gf180mcu_fd_ip_sram)
	MACROS = 5v
else
	MACROS = 3v3
endif

SLOT_DEFINE = SLOT_$(shell echo $(SLOT) | tr '[:lower:]' '[:upper:]')
SRAM_DEFINE = SRAM_$(SRAM)

LIBRELANE_OPTS = --pdk ${PDK} --pdk-root ${PDK_ROOT} --manual-pdk --scl ${SCL} --pad ${PAD}
LIBRELANE_CONFIGS = librelane/slots/slot_${SLOT}.yaml librelane/macros/macros_${MACROS}.yaml librelane/config.yaml

.DEFAULT_GOAL := help

help: ## Show this help message
	@echo 'Usage: make [target]'
	@echo ''
	@echo 'Available targets:'
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "  %-20s %s\n", $$1, $$2}'
.PHONY: help

all: librelane ## Build the project (runs LibreLane)
.PHONY: all

$(PDK_ROOT)/ciel/gf180mcu/versions/$(PDK_COMMIT)/$(PDK):
	ciel enable $(PDK_COMMIT) --pdk-root $(PDK_ROOT) --pdk-family $(PDK) --include-libraries all

clone-pdk: $(PDK_ROOT)/ciel/gf180mcu/versions/$(PDK_COMMIT)/$(PDK) ## Clone the GF180MCU PDK
.PHONY: clone-pdk

gen-defines:
	@echo "Writing src/generated_defines.svh"
	@echo "// This file is auto-generated by the Makefile" > src/generated_defines.svh
	@echo '`define ${SLOT_DEFINE}' >> src/generated_defines.svh
	@echo '`define ${SRAM_DEFINE}' >> src/generated_defines.svh
.PHONY: gen-defines

librelane: clone-pdk gen-defines ## Run LibreLane flow (synthesis, PnR, verification)
	SRAM_DEFINE=${SRAM_DEFINE} librelane ${LIBRELANE_CONFIGS} ${LIBRELANE_OPTS} --save-views-to $(MAKEFILE_DIR)/final
.PHONY: librelane

librelane-condensed: clone-pdk gen-defines ## Run LibreLane flow condensed (for CI)
	SRAM_DEFINE=${SRAM_DEFINE} librelane --condensed ${LIBRELANE_CONFIGS} ${LIBRELANE_OPTS} --save-views-to $(MAKEFILE_DIR)/final
.PHONY: librelane-condensed

librelane-nodrc: clone-pdk gen-defines ## Run LibreLane flow without DRC checks
	SRAM_DEFINE=${SRAM_DEFINE} librelane ${LIBRELANE_CONFIGS} ${LIBRELANE_OPTS} --save-views-to $(MAKEFILE_DIR)/final --skip KLayout.Antenna --skip KLayout.DRC --skip Magic.DRC
.PHONY: librelane-nodrc

librelane-klayoutdrc: clone-pdk gen-defines ## Run LibreLane flow without magic DRC checks
	SRAM_DEFINE=${SRAM_DEFINE} librelane ${LIBRELANE_CONFIGS} ${LIBRELANE_OPTS} --save-views-to $(MAKEFILE_DIR)/final --skip Magic.DRC
.PHONY: librelane-klayoutdrc

librelane-magicdrc: clone-pdk gen-defines ## Run LibreLane flow without KLayout DRC checks
	SRAM_DEFINE=${SRAM_DEFINE} librelane ${LIBRELANE_CONFIGS} ${LIBRELANE_OPTS} --save-views-to $(MAKEFILE_DIR)/final --skip KLayout.DRC
.PHONY: librelane-magicdrc

librelane-openroad: clone-pdk gen-defines ## Open the last run in OpenROAD
	SRAM_DEFINE=${SRAM_DEFINE} librelane ${LIBRELANE_CONFIGS} ${LIBRELANE_OPTS} --last-run --flow OpenInOpenROAD
.PHONY: librelane-openroad

librelane-klayout: clone-pdk gen-defines ## Open the last run in KLayout
	SRAM_DEFINE=${SRAM_DEFINE} librelane ${LIBRELANE_CONFIGS} ${LIBRELANE_OPTS} --last-run --flow OpenInKLayout
.PHONY: librelane-klayout

librelane-padring: clone-pdk gen-defines ## Only create the padring
	PDK_ROOT=${PDK_ROOT} PDK=${PDK} python3 scripts/padring.py ${LIBRELANE_CONFIGS}
.PHONY: librelane-padring

sim: ## Run RTL simulation with cocotb (chip_top wrapper)
	cd cocotb; PDK_ROOT=${PDK_ROOT} PDK=${PDK} SLOT=${SLOT} python3 chip_top_tb.py
.PHONY: sim

sim-core: ## Run chip_core end-to-end cocotb test (boot + PDM audio + KWS)
	$(MAKE) -C cocotb sim-core SLOT=${SLOT} KWS_KEYWORD="${KWS_KEYWORD}" KWS_SAMPLE_INDEX="${KWS_SAMPLE_INDEX}" KWS_SAMPLE_MATCH="${KWS_SAMPLE_MATCH}" KWS_MANIFEST_JSON="${KWS_MANIFEST_JSON}"
.PHONY: sim-core

sim-gl: ## Run gate-level simulation with cocotb (after copy-final)
	$(MAKE) -C cocotb sim-gl SLOT=${SLOT} KWS_KEYWORD="${KWS_KEYWORD}" KWS_SAMPLE_INDEX="${KWS_SAMPLE_INDEX}" KWS_SAMPLE_MATCH="${KWS_SAMPLE_MATCH}" KWS_MANIFEST_JSON="${KWS_MANIFEST_JSON}"
.PHONY: sim-gl

sim-gl-sdf: ## Run gate-level simulation with SDF back-annotated timing
	$(MAKE) -C cocotb sim-gl-sdf SLOT=${SLOT} $(if ${SDF_CORNER},SDF_CORNER="${SDF_CORNER}") KWS_KEYWORD="${KWS_KEYWORD}" KWS_SAMPLE_INDEX="${KWS_SAMPLE_INDEX}" KWS_SAMPLE_MATCH="${KWS_SAMPLE_MATCH}" KWS_MANIFEST_JSON="${KWS_MANIFEST_JSON}"
.PHONY: sim-gl-sdf

sim-view: ## View simulation waveforms in GTKWave
	gtkwave cocotb/sim_build/chip_top.fst
.PHONY: sim-view

copy-final: ## Copy final output files from the last run
	rm -rf final/
	cp -r librelane/runs/${RUN_TAG}/final/ final/
.PHONY: copy-final

render-image: ## Render an image from the final layout (after copy-final)
	mkdir -p img/
	PDK_ROOT=${PDK_ROOT} PDK=${PDK} python3 scripts/lay2img.py final/gds/${TOP}.gds img/${TOP}.png --width 2048 --oversampling 4
.PHONY: render-image