# scripts/gen_twiddle.py
import numpy as np

def gen_twiddle_rom(N=256, dw=16):
    """
    Generate quarter-wave cosine twiddle table for R2FFT.
    N        : FFT length
    dw       : data bitwidth (16 → Q1.15)
    Returns list of unsigned 16-bit integers.
    """
    n_entries = N // 4          # 64 for N=256
    scale     = (1 << (dw-1)) - 1   # 32767 for Q1.15

    entries = []
    for k in range(n_entries):
        val  = np.cos(2 * np.pi * k / N)
        q    = int(np.round(val * scale))
        q    = max(-(1 << (dw-1)), min((1 << (dw-1))-1, q))  # clamp
        entries.append(q & 0xFFFF)   # store as unsigned
    return entries

def verify_entries(entries, N=256, dw=16):
    """Spot-check known values."""
    scale = (1 << (dw-1)) - 1
    checks = {
        0:  scale,           # cos(0)      = 1.0   → 0x7FFF
        16: int(np.round(np.cos(2*np.pi*16/N) * scale)),  # cos(π/8)
        32: int(np.round(np.cos(2*np.pi*32/N) * scale)),  # cos(π/4) ≈ 0x5A82
        48: int(np.round(np.cos(2*np.pi*48/N) * scale)),  # cos(3π/8)
        63: int(np.round(np.cos(2*np.pi*63/N) * scale)),  # near cos(π/2)≈0
    }
    print("Spot checks:")
    for k, expected in checks.items():
        got = entries[k] if entries[k] < 32768 else entries[k] - 65536
        exp = expected
        ok  = abs(got - exp) <= 1
        print(f"  k={k:2d}: expected {exp:6d} ({exp&0xFFFF:#06x}), "
              f"got {got:6d} ({got&0xFFFF:#06x})  {'OK' if ok else 'FAIL'}")

if __name__ == "__main__":
    entries = gen_twiddle_rom(N=256, dw=16)
    verify_entries(entries, N=256, dw=16)

    with open("../rtl/fft_twiddle_rom.sv", "w") as f:
        f.write("// Auto-generated by scripts/gen_twiddle.py — DO NOT EDIT\n")
        f.write("module fft_twiddle_rom (\n")
        f.write("    input  wire       clk,\n")
        f.write("    input  wire       twact,\n")
        f.write("    input  wire [5:0] twa,\n")
        f.write("    output reg [15:0] twdr_cos\n")
        f.write(");\n")
        f.write("    always @(posedge clk) begin\n")
        f.write("        if (twact) begin\n")
        f.write("            case (twa)\n")
        for k, v in enumerate(entries):
            signed_v = v if v < 32768 else v - 65536
            f.write(f"                6'd{k}: twdr_cos <= 16'h{v:04X};"
                    f"  // {signed_v/32767:+.6f}\n")
        f.write("                default: twdr_cos <= 16'h0000;\n")
        f.write("            endcase\n")
        f.write("        end\n")
        f.write("    end\n")
        f.write("endmodule\n")

    # --- Output 2: Plain hex file (for reference/debug) ---
    with open("twiddle.hex", "w") as f:             # was "rtl/fft/twiddle.hex"
        for v in entries:
            f.write(f"{v:04X}\n")

    print(f"\nGenerated {len(entries)} entries")
    print("  → rtl/fft/twiddle_rom_body.svh")
    print("  → rtl/fft/twiddle.hex")