#!/usr/bin/env python3
"""Generate full_demo cfg.hex from a trained DSCNN model."""
from __future__ import annotations

import argparse
import sys
from pathlib import Path


# Allow `from rtl_golden import load_layer_cfgs` regardless of cwd.
_REPO_ROOT = Path(__file__).resolve().parents[4]
sys.path.insert(0, str(_REPO_ROOT / "rtl" / "dscnn" / "kws_top"))
from rtl_golden import load_layer_cfgs   # type: ignore


def emit_layer_cfg(layer: int, in_ch: int, out_ch: int, kH: int, kW: int,
                   sh: int, sw: int, ph: int, pw: int, dw: int, w_off: int,
                   mult: int, shift: int, relu: int,
                   ofmap_h: int, ofmap_w: int, bias_off: int) -> list[tuple[int, int]]:
    """Return byte writes for one layer."""
    base = layer << 4
    pairs: list[tuple[int, int]] = []
    pairs.append((base | 0x0, in_ch & 0xFF))
    pairs.append((base | 0x1, out_ch & 0xFF))
    pairs.append((base | 0x2, kH & 0x0F))
    pairs.append((base | 0x3, kW & 0x0F))
    pairs.append((base | 0x4, sh & 0x03))
    pairs.append((base | 0x5, sw & 0x03))
    pairs.append((base | 0x6, ph & 0x0F))
    pairs.append((base | 0x7, pw & 0x0F))
    pairs.append((base | 0x8, dw & 0x01))
    pairs.append((base | 0x9, w_off & 0xFF))
    pairs.append((base | 0xA, (w_off >> 8) & 0x1F))
    pairs.append((base | 0xB, shift & 0x1F))
    # bit[0]=relu, bit[1]=bias_off[8] (32-filter model has bias_off >= 256)
    pairs.append((base | 0xC, (relu & 0x1) | ((bias_off >> 7) & 0x2)))
    pairs.append((base | 0xD, ofmap_h & 0xFF))
    pairs.append((base | 0xE, ofmap_w & 0xFF))
    pairs.append((base | 0xF, bias_off & 0xFF))

    # 32-bit multiply scaler at 0xA0+(layer*4) ... +3
    mult_base = 0xA0 + layer * 4
    for i in range(4):
        pairs.append((mult_base + i, (mult >> (8 * i)) & 0xFF))
    return pairs


_WEIGHTS_TO_FILTERS = {2352: 16, 4296: 24, 6752: 32}


def _infer_filters(scales_path: Path, override: int | None) -> int:
    if override is not None:
        return override
    weights_hex = scales_path.parent / "weights.hex"
    if not weights_hex.exists():
        raise SystemExit(f"--n-filters not given and {weights_hex} missing; "
                         "pass --n-filters explicitly.")
    n = sum(1 for line in weights_hex.read_text().splitlines() if line.strip())
    if n not in _WEIGHTS_TO_FILTERS:
        raise SystemExit(f"unexpected weight count {n} in {weights_hex}; "
                         "expected one of 2352/4296/6752. Pass --n-filters explicitly.")
    return _WEIGHTS_TO_FILTERS[n]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("scales", type=Path, help="path to scales.txt")
    ap.add_argument("-o", "--out", type=Path, default=Path("cfg.hex"))
    ap.add_argument("--n-filters", type=int, default=None, choices=[16, 24, 32],
                    help="Filter count. Auto-detected from sibling weights.hex if omitted.")
    args = ap.parse_args()

    n_filters = _infer_filters(args.scales, args.n_filters)
    layer_cfgs = load_layer_cfgs(args.scales, n_filters=n_filters)

    all_pairs: list[tuple[int, int]] = []
    for cfg in layer_cfgs:
        all_pairs.extend(emit_layer_cfg(*cfg))

    with args.out.open("w") as f:
        f.write("# Auto-generated by gen_cfg_hex.py\n")
        f.write(f"# scales: {args.scales}  n_filters={n_filters}\n")
        f.write(f"# layers: {len(layer_cfgs)}  pairs: {len(all_pairs)}\n")
        f.write("# format: addr  value  (both hex, byte-wide)\n")
        for addr, val in all_pairs:
            f.write(f"{addr:02X}  {val:02X}\n")

    print(f"Wrote {len(all_pairs)} cfg pairs across {len(layer_cfgs)} layers "
          f"to {args.out}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
