// Auto-generated by design_cic_comp_fir.py
/*
Architecture:
  * Type I symmetric FIR (linear phase, required for STFFT)
  * Pre-adder structure  → halves the number of multiply operations
  * CSD shift-add trees  → zero multiplier cells (hardwired shifts only)
I/O widths:
  IW  = input word width  (CIC output, truncated/rounded)
  CW  = coefficient bits  (14)
  OW  = output word width = IW + CW + ceil(log2(NTAPS)) + 1 guard
Integration:
  Connect CIC o_result (truncated to IW bits) → i_sample.
  i_ce   = 1 every 16 kHz clock (one sample per cycle at 16 kHz, or
           strobe if shared with a faster clock).
  o_result feeds directly into STFFT i_sample port.
*/

//     set_dont_use [get_lib_cells *MULT*]

`default_nettype none

module ciccomp_fir #(
    parameter NTAPS = 33,   // Total taps (must be odd)
    parameter IW    = 16,      // Input word width
    parameter CW    = 14,    // Coefficient word width
    parameter OW    = 37       // Output width = IW+CW+ceil(log2(NTAPS))+1
) (
    input  wire               i_clk,
    input  wire               i_reset,
    input  wire               i_ce,
    input  wire signed [IW-1:0] i_sample,
    output reg  signed [OW-1:0] o_result
);

    localparam M  = (NTAPS-1)/2;   // Index of centre tap
    localparam PW = IW + CW + 1;   // Pre-adder product width (before accumulate)

    // Delay line 
    reg signed [IW-1:0] sr [0:NTAPS-1];
    integer i;
    always @(posedge i_clk)
    if (i_reset) begin
        for (i = 0; i < NTAPS; i = i+1) sr[i] <= 0;
    end else if (i_ce) begin
        for (i = NTAPS-1; i > 0; i = i-1) sr[i] <= sr[i-1];
        sr[0] <= i_sample;
    end

    // Pre-adders (exploit symmetry: sr[k] + sr[NTAPS-1-k]) 
    wire signed [IW:0] sym [0:M];
    genvar k;
    generate
    for (k = 0; k < M; k = k+1) begin : PREADD
        assign sym[k] = $signed({sr[k][IW-1], sr[k]}) +
                        $signed({sr[NTAPS-1-k][IW-1], sr[NTAPS-1-k]});
    end
    endgenerate
    assign sym[M] = $signed({sr[M][IW-1], sr[M]});  // centre tap

    // CSD multiply (shift-add, no multiplier cells)
    // PW = IW+CW+1 = 31
    wire signed [OW-1:0] prod [0:M];

    // tap k=0: +11952  CSD: +2^14  -2^12  -2^8  -2^6  -2^4
    assign prod[0] = ($signed({{OW-IW-1{sym[0][IW]}}, sym[0]}) <<< 14) - ($signed({{OW-IW-1{sym[0][IW]}}, sym[0]}) <<< 12) - ($signed({{OW-IW-1{sym[0][IW]}}, sym[0]}) <<< 8) - ($signed({{OW-IW-1{sym[0][IW]}}, sym[0]}) <<< 6) - ($signed({{OW-IW-1{sym[0][IW]}}, sym[0]}) <<< 4);

    // tap k=1: -2084  CSD: -2^11  -2^5  -2^2
    assign prod[1] = -($signed({{OW-IW-1{sym[1][IW]}}, sym[1]}) <<< 11) - ($signed({{OW-IW-1{sym[1][IW]}}, sym[1]}) <<< 5) - ($signed({{OW-IW-1{sym[1][IW]}}, sym[1]}) <<< 2);

    // tap k=2: -77  CSD: -2^6  -2^4  +2^2  -2^0
    assign prod[2] = -($signed({{OW-IW-1{sym[2][IW]}}, sym[2]}) <<< 6) - ($signed({{OW-IW-1{sym[2][IW]}}, sym[2]}) <<< 4) + ($signed({{OW-IW-1{sym[2][IW]}}, sym[2]}) <<< 2) - $signed({{OW-IW-1{sym[2][IW]}}, sym[2]});

    // tap k=3: +699  CSD: +2^10  -2^8  -2^6  -2^2  -2^0
    assign prod[3] = ($signed({{OW-IW-1{sym[3][IW]}}, sym[3]}) <<< 10) - ($signed({{OW-IW-1{sym[3][IW]}}, sym[3]}) <<< 8) - ($signed({{OW-IW-1{sym[3][IW]}}, sym[3]}) <<< 6) - ($signed({{OW-IW-1{sym[3][IW]}}, sym[3]}) <<< 2) - $signed({{OW-IW-1{sym[3][IW]}}, sym[3]});

    // tap k=4: -845  CSD: -2^10  +2^8  -2^6  -2^4  +2^2  -2^0
    assign prod[4] = -($signed({{OW-IW-1{sym[4][IW]}}, sym[4]}) <<< 10) + ($signed({{OW-IW-1{sym[4][IW]}}, sym[4]}) <<< 8) - ($signed({{OW-IW-1{sym[4][IW]}}, sym[4]}) <<< 6) - ($signed({{OW-IW-1{sym[4][IW]}}, sym[4]}) <<< 4) + ($signed({{OW-IW-1{sym[4][IW]}}, sym[4]}) <<< 2) - $signed({{OW-IW-1{sym[4][IW]}}, sym[4]});

    // tap k=5: +802  CSD: +2^10  -2^8  +2^5  +2^1
    assign prod[5] = ($signed({{OW-IW-1{sym[5][IW]}}, sym[5]}) <<< 10) - ($signed({{OW-IW-1{sym[5][IW]}}, sym[5]}) <<< 8) + ($signed({{OW-IW-1{sym[5][IW]}}, sym[5]}) <<< 5) + ($signed({{OW-IW-1{sym[5][IW]}}, sym[5]}) <<< 1);

    // tap k=6: -680  CSD: -2^9  -2^7  -2^5  -2^3
    assign prod[6] = -($signed({{OW-IW-1{sym[6][IW]}}, sym[6]}) <<< 9) - ($signed({{OW-IW-1{sym[6][IW]}}, sym[6]}) <<< 7) - ($signed({{OW-IW-1{sym[6][IW]}}, sym[6]}) <<< 5) - ($signed({{OW-IW-1{sym[6][IW]}}, sym[6]}) <<< 3);

    // tap k=7: +533  CSD: +2^9  +2^4  +2^2  +2^0
    assign prod[7] = ($signed({{OW-IW-1{sym[7][IW]}}, sym[7]}) <<< 9) + ($signed({{OW-IW-1{sym[7][IW]}}, sym[7]}) <<< 4) + ($signed({{OW-IW-1{sym[7][IW]}}, sym[7]}) <<< 2) + $signed({{OW-IW-1{sym[7][IW]}}, sym[7]});

    // tap k=8: -390  CSD: -2^9  +2^7  -2^3  +2^1
    assign prod[8] = -($signed({{OW-IW-1{sym[8][IW]}}, sym[8]}) <<< 9) + ($signed({{OW-IW-1{sym[8][IW]}}, sym[8]}) <<< 7) - ($signed({{OW-IW-1{sym[8][IW]}}, sym[8]}) <<< 3) + ($signed({{OW-IW-1{sym[8][IW]}}, sym[8]}) <<< 1);

    // tap k=9: +267  CSD: +2^8  +2^4  -2^2  -2^0
    assign prod[9] = ($signed({{OW-IW-1{sym[9][IW]}}, sym[9]}) <<< 8) + ($signed({{OW-IW-1{sym[9][IW]}}, sym[9]}) <<< 4) - ($signed({{OW-IW-1{sym[9][IW]}}, sym[9]}) <<< 2) - $signed({{OW-IW-1{sym[9][IW]}}, sym[9]});

    // tap k=10: -169  CSD: -2^7  -2^5  -2^3  -2^0
    assign prod[10] = -($signed({{OW-IW-1{sym[10][IW]}}, sym[10]}) <<< 7) - ($signed({{OW-IW-1{sym[10][IW]}}, sym[10]}) <<< 5) - ($signed({{OW-IW-1{sym[10][IW]}}, sym[10]}) <<< 3) - $signed({{OW-IW-1{sym[10][IW]}}, sym[10]});

    // tap k=11: +99  CSD: +2^7  -2^5  +2^2  -2^0
    assign prod[11] = ($signed({{OW-IW-1{sym[11][IW]}}, sym[11]}) <<< 7) - ($signed({{OW-IW-1{sym[11][IW]}}, sym[11]}) <<< 5) + ($signed({{OW-IW-1{sym[11][IW]}}, sym[11]}) <<< 2) - $signed({{OW-IW-1{sym[11][IW]}}, sym[11]});

    // tap k=12: -53  CSD: -2^6  +2^4  -2^2  -2^0
    assign prod[12] = -($signed({{OW-IW-1{sym[12][IW]}}, sym[12]}) <<< 6) + ($signed({{OW-IW-1{sym[12][IW]}}, sym[12]}) <<< 4) - ($signed({{OW-IW-1{sym[12][IW]}}, sym[12]}) <<< 2) - $signed({{OW-IW-1{sym[12][IW]}}, sym[12]});

    // tap k=13: +25  CSD: +2^5  -2^3  +2^0
    assign prod[13] = ($signed({{OW-IW-1{sym[13][IW]}}, sym[13]}) <<< 5) - ($signed({{OW-IW-1{sym[13][IW]}}, sym[13]}) <<< 3) + $signed({{OW-IW-1{sym[13][IW]}}, sym[13]});

    // tap k=14: -10  CSD: -2^3  -2^1
    assign prod[14] = -($signed({{OW-IW-1{sym[14][IW]}}, sym[14]}) <<< 3) - ($signed({{OW-IW-1{sym[14][IW]}}, sym[14]}) <<< 1);

    // tap k=15: +3  CSD: +2^2  -2^0
    assign prod[15] = ($signed({{OW-IW-1{sym[15][IW]}}, sym[15]}) <<< 2) - $signed({{OW-IW-1{sym[15][IW]}}, sym[15]});

    // tap k=16: -1  CSD: -2^0
    assign prod[16] = -$signed({{OW-IW-1{sym[16][IW]}}, sym[16]});

    // Accumulator
    always @(posedge i_clk)
    if (i_reset)
        o_result <= 0;
    else if (i_ce) begin
        o_result <= prod[0]
                    + prod[1]
                    + prod[2]
                    + prod[3]
                    + prod[4]
                    + prod[5]
                    + prod[6]
                    + prod[7]
                    + prod[8]
                    + prod[9]
                    + prod[10]
                    + prod[11]
                    + prod[12]
                    + prod[13]
                    + prod[14]
                    + prod[15]
                    + prod[16];
    end

endmodule