# Configuration for 7-Class Keyword Spotting
# Based on Google Speech Commands dataset

dataset:
  data_dir: "/home/dnocera/branch/ML-Audio/src/ml/Pipeline/speech_commands_v0.02"
#  data_dir: "/Users/diegonocera/Documents/ML-Audio/ML-Audio/src/ml/Pipeline/speech_commands_v0.02"
data:
  output_dir: "/home/dnocera/branch/ML-Audio/src/ml/output"
#  output_dir: "/Users/diegonocera/Documents/ML-Audio/ML-Audio/src/ml/output"
  classes:
    - "yes"
    - "no"
    - "on"
    - "off"
    - "wow"
    - "silence"
    - "unknown"

  target_keywords:
    - "yes"
    - "no"
    - "on"
    - "off"
    - "wow"

  include_silence: true
  num_silence_samples: 500
  unknown_max_train: 500
  unknown_max_val: 63
  unknown_max_test: 63
  random_seed: 42


preprocessing:
  sample_rate: 16000
  n_mels: 40
  n_fft: 256
  hop_length: 128
  window_length: 256

  #filters
  use_filters: false
  hpf_order: 2
  lpf_order: 4
  cutoff_hpf: 150
  cutoff_lpf: 4000

#ds-cnn
model:
  n_classes: 7  # yes, no, stop, go, silence, unknown
  
  # First convolution layer
  first_conv:
    filters: 24
    kernel_size: [10, 4]
    stride: [2, 2]
  
  # Depthwise Separable blocks
  ds_blocks:
    n_blocks: 4
    filters: 24
    kernel_size: [3, 3]
    stride: [1, 1]

training:
  n_epochs: 80
  batch_size: 64

  optimizer: "adam"
  learning_rate: 0.001
  weight_decay: 0.0005
  warmup_epochs: 5

  # Float warmup: epochs 1-49, QAT: epochs 50-80 (30 QAT epochs vs 18 before)
  qat_start_epoch: 50
  freeze_bn_epoch: 75

  lr_schedule:
    milestones: [25, 40, 55]
    gamma: 0.1
  val_every: 5

vad:
  calibration_duration: 2.0
  threshold_multiplier: 3.0
  default_energy_threshold: 0.0001

output:
  model_save_path: "/home/dnocera/branch/ML-Audio/src/ml/models/dscnn-pow2-v4/dscnn-pow2-v5.pt"
  log_file: "/home/dnocera/branch/ML-Audio/src/ml/models/dscnn-pow2-v4/training_log_pow2_v5.txt"
